pipeline {
    agent any
    stages {
        stage('clean') {
            steps {
                sh '/Applications/maven3.6.1/bin/mvn clean'
            }
        }
        stage('package') {
            steps {
                sh '/Applications/maven3.6.1/bin/mvn package -Dmaven.test.skip=true'
            }
        }
        stage('deploy') {
            steps {
                sh '/Applications/maven3.6.1/bin/mvn deploy -Dmaven.test.skip=true'
            }
        }
    }
}
